# Generated by Django 6.0.5 on 2026-05-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_sizes_gender_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postalCode',
        ),
    ]
