# Generated by Django 6.0.5 on 2026-06-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
